### ISSUE TITLE
Plot TopDownSets

### ISSUE THREAD

**Issue by sgibb** [sgibb/topdownr#70]
There is a new method `plot` now. Currently it just supports a single condition/spectrum, e.g.:
```r
library("topdownr")

H <- 1.0078250321
myoglobin <- readTopDownFiles(
    ## directory path
    path = topdownrdata::topDownDataPath("myoglobin"),
    ## fragmentation types
    type = c("a", "b", "c", "x", "y", "z"),
    ## adducts (add -H/H to c/z and name
    ## them cmH/zpH (c minus H, z plus H)
    adducts = data.frame(
        mass=c(-H, H),
        to=c("c", "z"),
        name=c("cmH", "zpH")),
    ## initiator methionine removal
    modifications = "Met-loss",
    ## don't use neutral loss
    neutralLoss = NULL,
    ## tolerance for fragment matching
    tolerance = 5e-6
)

plot(myoglobin[, 1])
```

![1](https://user-images.githubusercontent.com/1828443/34446834-d0749124-ecde-11e7-96a6-53b4b487b0b0.png)

```r
plot(myoglobin[, 2])
```
![2](https://user-images.githubusercontent.com/1828443/34446841-d7a6720a-ecde-11e7-9e43-9c558e63209a.png)

For an interactive version you could install `plotly`: 
```r
library("plotly")
plot(myoglobin[, 2])
ggplotly()
```

TODO: More documentation and an example in the vignette

@pavel-shliaha Do you have any further requests?

Possible ideas: Add a filename argument to `plot`. If given all conditions could be plotted into the file, e.g. `plot(myoglobin, file="myoglobin.pdf")`. What do you think?

**Comment by pavel-shliaha** [comment]
Yes please )))). Could you please make the function create a dataframe which contains mz, intensity and assignment if possible. E.g.:

```
xx <- plot(myoglobin[, 2])
xx
```
will return this dataframe.

the request is similar in principle to  

```
xx <- hist (rnorm(1000))
xx
```

**Comment by sgibb** [comment]
Currently I use `ggplot` and `plot` returns a `ggplot` object that could be further modified. I could change it to return a `data.frame` but than you can't change the plots anymore. 

I could implement another function `as.data.frame` that converts an `TopDownSet` into a `data.frame` with `mz`, `intensity`, `fragment name` column (but the result would need a lot of memory if we use all mz/intensity pairs from the original spectrum file).

**Comment by sgibb** [comment]
Unfortunately I can't reproduce this error. But while investigating it I recognized I messed up with `Scan` number, `acquisitionNumber` and `SpectrumIndex`. So if you wanted to plot the first condition it looked at the `Scan` number and searched for the `Scan`th spectrum in the file (`Scan` number is never equal to `SpectrumIndex` in the file) and showed you the wrong one. This is now fixed.

Could you please update `topdownr` and try your code again. If it fails please provide me the output of `traceback()` (just call it after the error occurred).

BTW: I changed the implementation of `plot` slightly. Now you can plot one or more (=all) conditions (takes a lot of time). `plot` always returns a list of `ggplot` objects. You can modify them or use `ggplotly` to investigate them interactively.

```r
## condition 1
plot(tds[,1])

## condition 1 and 2 (store the ggplot results in a list `gg`)
gg <- plot(tds[, 1:2])
library("cowplot")
do.call(plot_grid, gg)

## all conditions
pdf("topdownspectra.pdf", paper="a4r", width=12)
plot(tds)
dev.off()
```

Internal there is a new function `.condition2data.frame` that returns a `data.frame` with the columns `mz`, `intensity`, `fragment` (name, e.g. y24), `type` (e.g. "C-terminal"). I am not sure whether we should export this function to the regular user. But if you want to investigate the spectra yourself more easily you could call:

```r
d <- lapply(seq_len(ncol(tds)), function(i)topdownr:::.condition2data.frame(tds[,i]))
# the three `:` between topdownr and condition2data.frame are needed to
# access an internal hidden function
```

**Comment by pavel-shliaha** [comment]
still get the same problem. I realised that our scans might not directly correspond since i used a different sampleColumns vector. Could you please run this:
```

sampleColumns <- c("Mz", "AgcTarget",  "UvpdActivation", "EtdReagentTarget",   "EtdActivation", "CidActivation",   "HcdActivation")

CA <-  readTopDownFiles(path = getwd(),
                               type = c("a", "b", "c", "x", "y", "z"),
                               adducts = data.frame(mass=c(-H, -H, H, H), name=c("amH","cmH", "zpH", "xpH"), to=c("a", "c", "z", "x")),
                               neutralLoss = NULL,
                               modifications = c("Carbamidomethyl", "Acetyl", "Met-loss"),
                               sampleColumns = sampleColumns,
                               tolerance = 5e-6) 

plot (CA[, 1])
plot (CA[, 100])
```
`
> traceback ()`

7: openMSfile(file)
6: .readSpectrum(object@files[grep(paste0(object$File[1L], .topDownFileExtRx("mzml")), 
       object@files)], object$SpectrumIndex[1L])
5: .condition2data.frame(x)
4: .plot(x[, i])
3: .local(x, y, ...)
2: plot(CA[, 100])
1: plot(CA[, 100])

**Comment by sgibb** [comment]
Wired, works for me: Could you please also provide me the output of `CA@files` and  `CA$Files[100]`?

**Comment by pavel-shliaha** [comment]
c("M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+06_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+06_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+07_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+07_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_5e+06_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_5e+06_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+06_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+06_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+07_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+07_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_5e+06_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_5e+06_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+06_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+06_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+07_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+07_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_5e+06_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_5e+06_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_missing_scans_1.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_missing_scans_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_1162_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_1162_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_745_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_745_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_908_.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_908_2.experiments.csv", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA.fasta", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+06_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+06_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+07_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+07_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_5e+06_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_5e+06_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+06_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+06_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+07_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+07_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_5e+06_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_5e+06_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+06_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+06_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+07_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+07_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_5e+06_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_5e+06_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_missing_scans_1.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_missing_scans_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_1162_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_1162_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_745_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_745_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_908_.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_908_2.mzML", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+06_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+06_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+07_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_1e+07_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_5e+06_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_1162_ETDReagentTarget_5e+06_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+06_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+06_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+07_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_1e+07_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_5e+06_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_745_ETDReagentTarget_5e+06_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+06_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+06_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+07_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_1e+07_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_5e+06_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_908_ETDReagentTarget_5e+06_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_missing_scans_1.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_missing_scans_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_1162_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_1162_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_745_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_745_2.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_908_.txt", 
"M:\\r_scripts\\2017_01_18_top_down_lumos_first_large_experiment\\2017_07_03_CA\\raw\\CA_UVPD_908_2.txt"
)

**Comment by pavel-shliaha** [comment]
> CA@files[100]
[1] NA

**Comment by pavel-shliaha** [comment]
> CA[, 100]

works:


TopDownSet object (0.43 Mb)
- - - Protein data - - -
Amino acid sequence (259): SHHWGYGKHNGPEHWHKDFPIANGERQSPVDIDTKAVVQDPALKPLA...PISVSSQQMLKFRTLNFNAEGEPELLMLANWRPAQPLKNRQVRGFPK 
Mass : 28988.67
Modifications (3): Carbamidomethyl, Acetyl, Met-loss
- - - Fragment data - - -
Number of theoretical fragments: 2580 
Theoretical fragment types (6): a, b, c, x, y, z
Theoretical mass range: [101.05;28905.63]
- - - Condition data - - -
Number of conditions: 1 
Number of scans: 1 
Condition variables (91): File, Scan, ..., Sample, MedianIonInjectionTimeMs
- - - Intensity data - - -
Size of array: 2580x1 (2.25% != 0)
Number of matched fragments: 58 
Intensity range: [10266.93;2757974.25]
- - - Processing information - - -
[2018-01-15 12:57:09] 287787 fragments [2580;6309] matched (tolerance: 5 ppm).
[2018-01-15 12:57:09] Condition names updated based on: Mz, AgcTarget, UvpdActivation, EtdReagentTarget, EtdActivation, CidActivation, HcdActivation. Order of conditions changed. 1917 conditions.
[2018-01-15 12:57:09] Recalculate median injection time based on: Mz, AgcTarget.
[2018-01-15 15:16:21] Subsetted 287787 fragments [2580;6309] to 58 fragments [2580;1].

**Comment by sgibb** [comment]
Should be `CA$Files[100]` not `CA@files[100]`, everything else looks quite good.

**Comment by pavel-shliaha** [comment]
CA@colData$File[100]

returns

character-Rle of length 1 with 1 run
  Lengths:                                1
  Values : "CA_745_ETDReagentTarget_1e+06_"

**Comment by pavel-shliaha** [comment]
CA[, 100]

> CA[, 100]
TopDownSet object (0.43 Mb)
- - - Protein data - - -
Amino acid sequence (259): SHHWGYGKHNGPEHWHKDFPIANGERQSPVDIDTKAVVQDPALKPLA...PISVSSQQMLKFRTLNFNAEGEPELLMLANWRPAQPLKNRQVRGFPK 
Mass : 28988.67
Modifications (3): Carbamidomethyl, Acetyl, Met-loss
- - - Fragment data - - -
Number of theoretical fragments: 2580 
Theoretical fragment types (6): a, b, c, x, y, z
Theoretical mass range: [101.05;28905.63]
- - - Condition data - - -
Number of conditions: 1 
Number of scans: 1 
Condition variables (91): File, Scan, ..., Sample, MedianIonInjectionTimeMs
- - - Intensity data - - -
Size of array: 2580x1 (2.25% != 0)
Number of matched fragments: 58 
Intensity range: [10266.93;2757974.25]
- - - Processing information - - -
[2018-01-15 12:57:09] 287787 fragments [2580;6309] matched (tolerance: 5 ppm).
[2018-01-15 12:57:09] Condition names updated based on: Mz, AgcTarget, UvpdActivation, EtdReagentTarget, EtdActivation, CidActivation, HcdActivation. Order of conditions changed. 1917 conditions.
[2018-01-15 12:57:09] Recalculate median injection time based on: Mz, AgcTarget.
[2018-01-15 17:10:14] Subsetted 287787 fragments [2580;6309] to 58 fragments [2580;1].

**Comment by sgibb** [comment]
JFTR: the error just happens for filenames with special characters (e.g. `+` that have special meanings in regular expressions). Fixed in abb63c1c5d08a7a29ad9e158509f9d96df537bd9

@pavel-shliaha Could you please try the newest `topdownr`?

**Comment by pavel-shliaha** [comment]
could you please clarify how plotting works? Will you only label fragments that are in the TopDownSet or is the matching performed all over, when the plotting function is called?

**Comment by sgibb** [comment]
Stupid me. I ignored the fragments in the `TopDownSet` completely before. The matching is performed again with each call of `plot` (with the same settings as in `readTopDownSet`). That is necessary because I don't store the original mz values but just the theoretical fragment mz values. So we have two possibilities: 1. do the matching again, 2. avoid the matching and plot the spectrum mz and the fragment mz independently (there would be a small gap between them in larger zoom levels). I used the first option. And now just fragments that are present after filtering etc. are plotted:

```r
library("topdownr")
library("cowplot")
plot_grid(
    plot(myoglobin[,1])[[1]],
    plot(filterIntensity(myoglobin[,1], 5e4, relative=FALSE))[[1]],
    plot(filterIntensity(myoglobin[,1], 5e5, relative=FALSE))[[1]],
    plot(filterIntensity(myoglobin[,1], 5e6, relative=FALSE))[[1]],
    labels=paste("Threshold:", c(0, 5*10^(4:6))),
    nrow=4
)
```
![grid](https://user-images.githubusercontent.com/1828443/35470914-3cc6c49e-0352-11e8-8a87-c38aa5089b13.png)

**Comment by pavel-shliaha** [comment]
I am very sorry to request this, but is there a way to geuinely combine ggplot2 objects together (not by cowplot). The reason I am asking is that if I want to plot say 3 plot they have different mz ranges and I would like to plot them on top of each other.

**Comment by pavel-shliaha** [comment]
Yes I can see the problem.  I think we discussed this before, but how complicated is it to add another 2 tables (mz and ppm error to the object)? So you have 3 tables. This seems like a good long term solution

**Comment by sgibb** [comment]
Neither `grid_arrange` nor `cowplot` is sufficient? What do you mean by plot them on top of each other (vertical or all three spectra in the same plot? Could you maybe provide a small sketch?)

Regarding mz/ppm error. It is not damn complicated but will take some time because I need to touch nearly every function and it will nearly triple the memory usage (BTW: we don't need to store the ppm part. If we store mz and the theoretical mz from the fragments we could easily calculate the ppm error if needed). If you think it is really necessary I will do it.

**Comment by sgibb** [comment]
While thinking about it a little bit longer I can't see a real benifit of storing the original mz values. For plotting we would also need to read the whole spectrum (not just the matched peaks) and subsequently I have to call `match` anyway (which would be just a little bit faster than the current `.matchFragments`). Maybe there will be a use case for the original mz values somewhere in the future but currently I can't find any.
